# Generated by Django 5.1 on 2025-10-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioYouTube',
            fields=[
                ('id_comentario', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('id_video', models.CharField(max_length=255)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('texto_del_comentario', models.TextField()),
                ('fecha', models.DateField()),
                ('likes_comentario', models.IntegerField(default=0)),
            ],
        ),
    ]
